if (message.content === `${prefix}botinfo`) {
  message.channel.send()
       const duration = moment.duration(" D [days], H [hrs], m [mins], s [secs]");
       const embedStats = new Discord.RichEmbed()
           .setAuthor(client.user.username)
           .setTitle("***BOT Stats***")
           .setColor("RANDOM")
           .addField("• Mem Usage", `${(process.memoryUsage().heapUsed / 1024 / 1024).toFixed(2)} / ${(os.totalmem() / 1024 / 1024).toFixed(2)} MB`, true)
           .addField("• Uptime ", `${duration}`, true)
           .addField("• Users", `${client.users.size.toLocaleString()}`, true)
           .addField("• Servers", `${client.guilds.size.toLocaleString()}`, true)
           .addField("• Channels ", `${client.channels.size.toLocaleString()}`, true)
           .addField("• Discord.js", `v${version}`, true)
           .addField("• Node", `${process.version}`, true)
           .addField("• CPU", `\`\`\`md\n${os.cpus().map(i => `${i.model}`)[0]}\`\`\``)
           .addField("• Arch", `\`${os.arch()}\``, true)
           .addField("• Platform", `\`\`${os.platform()}\`\``, true)
           .addField("API Latency", `${Math.round(client.ping)}ms`)
       message.channel.send(embedStats)
   }
